[package]
name = "ilo_sona"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicase = "2.6.0"
toki_sama = { path = "../toki_sama" }